### ISSUE TITLE
Использование Maven для сборки

### ISSUE THREAD

**Issue by dgroup** [dromenskyi/nc.edu.group8.lb4#1]

**Comment by hdls** [comment]
а может все таки использовать Ant?

**Comment by dromenskyi** [comment]
а в чем сложность? Пойми, просто когда начнешь  работать, знания анта тебе пригодятся постолько-поскольку, а Мавен используется как основной инструмент

**Comment by dgroup** [comment]
Ну как получилось собрать? :)

**Comment by dromenskyi** [comment]
Создал ветку dev с новой структурой и настройкой мавена. Работает, собирается, тесты проходит
