### ISSUE TITLE
Зачем выделять имя таблицы в отдельную переменную, если она используется только в запросах?

### ISSUE THREAD

**Issue by dgroup** [dromenskyi/nc.edu.group8.lb4#10]
https://github.com/colitman/nc.edu.group8.lb4/blob/master/module-ejb/src/main/java/beans/city/CityBean.java

**Comment by dromenskyi** [comment]
для того, чтобы если вдруг поменяется имя таблицы, поменять его в одном месте - в верху класса

**Comment by dgroup** [comment]
Вообще я хотел что бы все CRUD запросы были выделены в отдельные константы... Это кажется мне удобным.

**Comment by dromenskyi** [comment]
или будет лучше для delete, select_by_pk и select_all запросов сделать утилитный класс с final static константами, т.к. они (запросы) у нас одинаковые для всех сущностей?

**Comment by dromenskyi** [comment]
хотя делать отдельный класс для 3 констант как-то "занадто" мне кажется :)

**Comment by dgroup** [comment]
да, занадто... выдели в каждом класе

**Comment by dromenskyi** [comment]
так уже каг-бэ :confused:  @dgroup глянь, плиз, коммит мой (выше ссылка), если всё норм, то тикет можно закрывать, я думаю
