### ISSUE TITLE
А если при обновлении объект уже имеет такие же параметры - зачем кидать EJBException ?

### ISSUE THREAD

**Issue by dgroup** [dromenskyi/nc.edu.group8.lb4#11]
https://github.com/colitman/nc.edu.group8.lb4/blob/master/module-ejb/src/main/java/beans/country/CountryBean.java
....

``` 'java
private void storeInstance() throws SQLException {
            int rowsUpd = stm.executeUpdate();

            if(rowsUpd == 0) {
                throw new EJBException("Updating country with ID = " + ID + " failed.");
            }
....
```

**Comment by dgroup** [comment]
Ну уже есть такие параметры которые хочет юзер - нафиг его ексепшеном пугать?

**Comment by dromenskyi** [comment]
ибо нефиг :)

**Comment by dromenskyi** [comment]
ну так иксепшен будет выбрасываться ж если метод storeInstance() вызовется, а метод вызывается, если параметры изменились. Т.е. если параметры не изменились, то метод не вызовется => иксепшен выбросится только в случае какой-то ошибки

**Comment by dgroup** [comment]
В случае какой ошибки? Уберите пожалуйста бессмысленную строчку...

**Comment by dromenskyi** [comment]
> В случае какой ошибки? 

ну, например такой, которой мы не можем предугадать. мало ли...

**Comment by dromenskyi** [comment]
не, ну ок, уберем, ноу проблем, но логгер на всяк случай все равно заставим записать)))

**Comment by dgroup** [comment]
Логер - это твой лучший друг :+1:
