### ISSUE TITLE
Зачем дженерики нужны?

### ISSUE THREAD

**Issue by dgroup** [dromenskyi/nc.edu.group8.lb4#13]
https://github.com/colitman/nc.edu.group8.lb4/tree/master/module-web/src/test/java/util/gateway

**Comment by hdls** [comment]
я могу поколупатся, ток боюсь паламать.

**Comment by dgroup** [comment]
Блин, это что за комент то такой, "я могу ... ток боюсь...". Ты разработчик этой фигни :) Давай правь/исправляй свои недочеты...

**Comment by dgroup** [comment]
Свои косяки исправлять намного приятней чем чужие)))

**Comment by dgroup** [comment]
:clap:
