### ISSUE TITLE
ServletPrototype... Может пора уже имя актуализировать?

### ISSUE THREAD

**Issue by dgroup** [dromenskyi/nc.edu.group8.lb4#14]
https://github.com/colitman/nc.edu.group8.lb4/blob/master/module-web/src/main/java/servlet/ServletPrototype.java

Только не вздумайте в Servlet переименовать ...) а то у вас фантазии много)

**Comment by dromenskyi** [comment]
блииин

**Comment by dromenskyi** [comment]
ахаха :smile:

**Comment by hdls** [comment]
а че? чет не так?

**Comment by dromenskyi** [comment]
Олег, обрати внимание на зависимости от имени сервлета. Имя класса то ты поменял, это да.
Как минимум это заафектит еще web-xml в module-web, т.к. там указыывается класс сервлета.

**Comment by hdls** [comment]
походу это ток в одном месте. Ща исправлю

**Comment by dgroup** [comment]
Все с вами ясно... Походу это бесполезно...

**Comment by dromenskyi** [comment]
а вот щас обидно было :disappointed:
