### ISSUE TITLE
EJBBeansGateway 

### ISSUE THREAD

**Issue by dgroup** [dromenskyi/nc.edu.group8.lb4#15]
https://github.com/colitman/nc.edu.group8.lb4/blob/master/module-web/src/main/java/hibernate/dao/EJBBeansGateway.java
- уберите дублирование кода
- замените ифы на фабрики...
- статическую информацию можно вынести в аннотации, и нацепить их на класы.
- динамическую компенсируете обработчиками и фабриками.

**Comment by hdls** [comment]
Честно, я без понятия как это сделать (
