### ISSUE TITLE
Java Server Page. Действие jsp:include

### ISSUE THREAD

**Issue by dgroup** [dromenskyi/nc.edu.group8.lb4#16]
http://www.java2ee.ru/jsp/include.html

``` js
<hr><div id="footer"></div>
<script type="text/javascript">
    $(function() {
        $("#header").load("header.html");
        $("#footer").load("footer.html");
    });
</script>
```

**Comment by dgroup** [comment]
Причем в другом месте: https://github.com/colitman/nc.edu.group8.lb4/blob/master/module-web/src/main/webapp/city/showAllInRegion.jsp

используется jstl:

``` java
<div id="header">
    <c:import url="/header.html"/>
</div><hr>
```

**Comment by dromenskyi** [comment]
аттавизм, видно пропустили когда меняли. откуда кусок с ява-скриптом?

**Comment by dgroup** [comment]
https://github.com/colitman/nc.edu.group8.lb4/blob/master/module-web/src/main/webapp/index.html

**Comment by dromenskyi** [comment]
@hdls , а у нас разве этот файл юзается? по-моему вместо него index.jsp в той же папке

**Comment by hdls** [comment]
да, не юзается. Оставил просто на всякий случай

**Comment by dgroup** [comment]
Удалите файлы, которые не используются....
