### ISSUE TITLE
Все комменты должны быть на буржуйском

### ISSUE THREAD

**Issue by dgroup** [dromenskyi/nc.edu.group8.lb4#18]
пример: https://github.com/colitman/nc.edu.group8.lb4/blob/master/module-web/src/main/webapp/javascript.js

**Comment by dromenskyi** [comment]
а по-моему по ссылке и так норм))) это ж эльфийский, Юра. не узнал?

**Comment by dromenskyi** [comment]
:+1:  :smile:

**Comment by dgroup** [comment]
Извините парни, я слабоват в эльфийском. Надо найти эльфийку что бы помогла подтянуть...
