### ISSUE TITLE
Bulk import & problems...

### ISSUE THREAD

**Issue by dgroup** [dromenskyi/nc.edu.group8.lb4#20]
``` java
import java.util.*;
import java.sql.*;
import hibernate.dao.*;
import hibernate.logic.*;
```

Пройдитесь по стриму и уберите такую радость.... Замените на конкретные класы...

Имеет смысл использовать такую конструкцию >5

**Comment by dromenskyi** [comment]
а резон? на перформанс это всё равно не влияет - классы подгружаются в память только еслит они реально используются

**Comment by dgroup** [comment]
вроде мелочь, а искать зависимости сложнее. У меня был прикол, чувак подтягивал в кастомной jsp кучу классов, и т.к. проект большой, было не совсем ясно из какой компоненты и вообще что за класс. Пришлось убить мин. 40, что бы определить откуда он пришел...

По этому лучше, что бы вы такого не писали
