### ISSUE TITLE
Нужно ли нам переписывать Actions?

### ISSUE THREAD

**Issue by dromenskyi** [dromenskyi/nc.edu.group8.lb4#4]
Сейчас в экшенах перед вызовом гейтвея явно создается объект-сущность из пакета hibernate.logic. далее этот объект передается в гейтвей. Как нам лучше поступить - переписать каким-то образом экшены или приспособить новый гейтвей к работе со старыми классами?

**Comment by dgroup** [comment]
1) Акшены не переписуются
2) Пишется новый гейтвей (которому будете скармливать сущность), для работы с бинами. Этот гейтвей должен заимлементить интерфейс Gateway.

**Comment by dromenskyi** [comment]
> Этот гейтвей должен заимлементить интерфейс Gateway

не. ну это ясно. класс EJBBeansGateway с временными заглушками методов я добавлял.
Ок.
